// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Agendaproduccion struct {
	ID          int64
	Fecha       string
	Responsable string
	Estado      string
}

type Cliente struct {
	ID       int64
	Nombre   string
	Telefono string
}

type Pedido struct {
	ID      int64
	Mensaje string
	Estado  string
}

type Personalizacion struct {
	ID       int64
	PedidoID int64
	Mensaje  string
	Color    string
}

type ProductoPersonalizado struct {
	ID       int64
	PedidoID int64
	Nombre   string
	Cantidad int64
	Precio   float64
}

type Reclamo struct {
	ID          int64
	ClienteID   int64
	PedidoID    int64
	Descripcion string
	Estado      string
}

type Seguimientopedido struct {
	ID          int64
	PedidoID    int64
	Estado      string
	FechaEstado string
}

type Slotproduccion struct {
	ID               int64
	AgendaID         int64
	CapacidadMaxima  int64
	PedidosAsignados int64
}

type Solicitudurgente struct {
	ID             int64
	Cliente        string
	Descripcion    string
	FechaRequerida string
	Estado         string
}
