// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarAgendaProduccion = `-- name: ActualizarAgendaProduccion :one
UPDATE AgendaProduccion
SET fecha = ?, responsable = ?, estado = ?
WHERE id = ?
RETURNING id, fecha, responsable, estado
`

type ActualizarAgendaProduccionParams struct {
	Fecha       string
	Responsable string
	Estado      string
	ID          int64
}

func (q *Queries) ActualizarAgendaProduccion(ctx context.Context, arg ActualizarAgendaProduccionParams) (Agendaproduccion, error) {
	row := q.db.QueryRowContext(ctx, actualizarAgendaProduccion,
		arg.Fecha,
		arg.Responsable,
		arg.Estado,
		arg.ID,
	)
	var i Agendaproduccion
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.Responsable,
		&i.Estado,
	)
	return i, err
}

const actualizarCliente = `-- name: ActualizarCliente :one
UPDATE cliente
SET nombre = ?, telefono = ?
WHERE id = ?
RETURNING id, nombre, telefono
`

type ActualizarClienteParams struct {
	Nombre   string
	Telefono string
	ID       int64
}

func (q *Queries) ActualizarCliente(ctx context.Context, arg ActualizarClienteParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, actualizarCliente, arg.Nombre, arg.Telefono, arg.ID)
	var i Cliente
	err := row.Scan(&i.ID, &i.Nombre, &i.Telefono)
	return i, err
}

const actualizarPedido = `-- name: ActualizarPedido :one
UPDATE pedido
SET mensaje = ?, estado = ?
WHERE id = ?
RETURNING id, mensaje, estado
`

type ActualizarPedidoParams struct {
	Mensaje string
	Estado  string
	ID      int64
}

func (q *Queries) ActualizarPedido(ctx context.Context, arg ActualizarPedidoParams) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, actualizarPedido, arg.Mensaje, arg.Estado, arg.ID)
	var i Pedido
	err := row.Scan(&i.ID, &i.Mensaje, &i.Estado)
	return i, err
}

const actualizarPersonalizacion = `-- name: ActualizarPersonalizacion :one
UPDATE personalizacion
SET pedido_id = ?, mensaje = ?, color = ?
WHERE id = ?
RETURNING id, pedido_id, mensaje, color
`

type ActualizarPersonalizacionParams struct {
	PedidoID int64
	Mensaje  string
	Color    string
	ID       int64
}

func (q *Queries) ActualizarPersonalizacion(ctx context.Context, arg ActualizarPersonalizacionParams) (Personalizacion, error) {
	row := q.db.QueryRowContext(ctx, actualizarPersonalizacion,
		arg.PedidoID,
		arg.Mensaje,
		arg.Color,
		arg.ID,
	)
	var i Personalizacion
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Mensaje,
		&i.Color,
	)
	return i, err
}

const actualizarProductoPersonalizado = `-- name: ActualizarProductoPersonalizado :one
UPDATE producto_personalizado
SET pedido_id = ?, nombre = ?, cantidad = ?, precio = ?
WHERE id = ?
RETURNING id, pedido_id, nombre, cantidad, precio
`

type ActualizarProductoPersonalizadoParams struct {
	PedidoID int64
	Nombre   string
	Cantidad int64
	Precio   float64
	ID       int64
}

func (q *Queries) ActualizarProductoPersonalizado(ctx context.Context, arg ActualizarProductoPersonalizadoParams) (ProductoPersonalizado, error) {
	row := q.db.QueryRowContext(ctx, actualizarProductoPersonalizado,
		arg.PedidoID,
		arg.Nombre,
		arg.Cantidad,
		arg.Precio,
		arg.ID,
	)
	var i ProductoPersonalizado
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Nombre,
		&i.Cantidad,
		&i.Precio,
	)
	return i, err
}

const actualizarReclamo = `-- name: ActualizarReclamo :one
UPDATE Reclamo
SET cliente_id = ?, pedido_id = ?, descripcion = ?, estado = ?
WHERE id = ?
RETURNING id, cliente_id, pedido_id, descripcion, estado
`

type ActualizarReclamoParams struct {
	ClienteID   int64
	PedidoID    int64
	Descripcion string
	Estado      string
	ID          int64
}

func (q *Queries) ActualizarReclamo(ctx context.Context, arg ActualizarReclamoParams) (Reclamo, error) {
	row := q.db.QueryRowContext(ctx, actualizarReclamo,
		arg.ClienteID,
		arg.PedidoID,
		arg.Descripcion,
		arg.Estado,
		arg.ID,
	)
	var i Reclamo
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.PedidoID,
		&i.Descripcion,
		&i.Estado,
	)
	return i, err
}

const actualizarSeguimientoPedido = `-- name: ActualizarSeguimientoPedido :one
UPDATE SeguimientoPedido
SET pedido_id = ?, estado = ?, fecha_estado = ?
WHERE id = ?
RETURNING id, pedido_id, estado, fecha_estado
`

type ActualizarSeguimientoPedidoParams struct {
	PedidoID    int64
	Estado      string
	FechaEstado string
	ID          int64
}

func (q *Queries) ActualizarSeguimientoPedido(ctx context.Context, arg ActualizarSeguimientoPedidoParams) (Seguimientopedido, error) {
	row := q.db.QueryRowContext(ctx, actualizarSeguimientoPedido,
		arg.PedidoID,
		arg.Estado,
		arg.FechaEstado,
		arg.ID,
	)
	var i Seguimientopedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Estado,
		&i.FechaEstado,
	)
	return i, err
}

const actualizarSlotProduccion = `-- name: ActualizarSlotProduccion :one
UPDATE slotProduccion
SET agenda_id = ?, capacidad_maxima = ?, pedidos_asignados = ?
WHERE id = ?
RETURNING id, agenda_id, capacidad_maxima, pedidos_asignados
`

type ActualizarSlotProduccionParams struct {
	AgendaID         int64
	CapacidadMaxima  int64
	PedidosAsignados int64
	ID               int64
}

func (q *Queries) ActualizarSlotProduccion(ctx context.Context, arg ActualizarSlotProduccionParams) (Slotproduccion, error) {
	row := q.db.QueryRowContext(ctx, actualizarSlotProduccion,
		arg.AgendaID,
		arg.CapacidadMaxima,
		arg.PedidosAsignados,
		arg.ID,
	)
	var i Slotproduccion
	err := row.Scan(
		&i.ID,
		&i.AgendaID,
		&i.CapacidadMaxima,
		&i.PedidosAsignados,
	)
	return i, err
}

const actualizarSolicitudUrgente = `-- name: ActualizarSolicitudUrgente :one
UPDATE SolicitudUrgente
SET cliente = ?, descripcion = ?, fecha_requerida = ?, estado = ?
WHERE id = ?
RETURNING id, cliente, descripcion, fecha_requerida, estado
`

type ActualizarSolicitudUrgenteParams struct {
	Cliente        string
	Descripcion    string
	FechaRequerida string
	Estado         string
	ID             int64
}

func (q *Queries) ActualizarSolicitudUrgente(ctx context.Context, arg ActualizarSolicitudUrgenteParams) (Solicitudurgente, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitudUrgente,
		arg.Cliente,
		arg.Descripcion,
		arg.FechaRequerida,
		arg.Estado,
		arg.ID,
	)
	var i Solicitudurgente
	err := row.Scan(
		&i.ID,
		&i.Cliente,
		&i.Descripcion,
		&i.FechaRequerida,
		&i.Estado,
	)
	return i, err
}

const borrarAgendaProduccion = `-- name: BorrarAgendaProduccion :execrows
DELETE FROM AgendaProduccion
WHERE id = ?
`

func (q *Queries) BorrarAgendaProduccion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarAgendaProduccion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarCliente = `-- name: BorrarCliente :execrows
DELETE FROM cliente
WHERE id = ?
`

func (q *Queries) BorrarCliente(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCliente, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarPedido = `-- name: BorrarPedido :execrows
DELETE FROM pedido
WHERE id = ?
`

func (q *Queries) BorrarPedido(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarPedido, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarPersonalizacion = `-- name: BorrarPersonalizacion :execrows
DELETE FROM personalizacion
WHERE id = ?
`

func (q *Queries) BorrarPersonalizacion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarPersonalizacion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarProductoPersonalizado = `-- name: BorrarProductoPersonalizado :execrows
DELETE FROM producto_personalizado
WHERE id = ?
`

func (q *Queries) BorrarProductoPersonalizado(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarProductoPersonalizado, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarReclamo = `-- name: BorrarReclamo :execrows
DELETE FROM Reclamo
WHERE id = ?
`

func (q *Queries) BorrarReclamo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarReclamo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSeguimientoPedido = `-- name: BorrarSeguimientoPedido :execrows
DELETE FROM SeguimientoPedido
WHERE id = ?
`

func (q *Queries) BorrarSeguimientoPedido(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSeguimientoPedido, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSlotProduccion = `-- name: BorrarSlotProduccion :execrows
DELETE FROM slotProduccion
WHERE id = ?
`

func (q *Queries) BorrarSlotProduccion(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSlotProduccion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSolicitudUrgente = `-- name: BorrarSolicitudUrgente :execrows
DELETE FROM SolicitudUrgente    
WHERE id = ?
`

func (q *Queries) BorrarSolicitudUrgente(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitudUrgente, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarAgendaProduccionPorID = `-- name: BuscarAgendaProduccionPorID :one
SELECT id, fecha, responsable, estado
FROM AgendaProduccion
WHERE id = ?
`

func (q *Queries) BuscarAgendaProduccionPorID(ctx context.Context, id int64) (Agendaproduccion, error) {
	row := q.db.QueryRowContext(ctx, buscarAgendaProduccionPorID, id)
	var i Agendaproduccion
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.Responsable,
		&i.Estado,
	)
	return i, err
}

const buscarClientePorID = `-- name: BuscarClientePorID :one
SELECT id, nombre, telefono
FROM cliente
WHERE id = ?
`

func (q *Queries) BuscarClientePorID(ctx context.Context, id int64) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, buscarClientePorID, id)
	var i Cliente
	err := row.Scan(&i.ID, &i.Nombre, &i.Telefono)
	return i, err
}

const buscarPedidoPorID = `-- name: BuscarPedidoPorID :one
SELECT id, mensaje, estado
FROM pedido
WHERE id = ?
`

func (q *Queries) BuscarPedidoPorID(ctx context.Context, id int64) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, buscarPedidoPorID, id)
	var i Pedido
	err := row.Scan(&i.ID, &i.Mensaje, &i.Estado)
	return i, err
}

const buscarPersonalizacionPorID = `-- name: BuscarPersonalizacionPorID :one
SELECT id, pedido_id, mensaje, color
FROM personalizacion
WHERE id = ?
`

func (q *Queries) BuscarPersonalizacionPorID(ctx context.Context, id int64) (Personalizacion, error) {
	row := q.db.QueryRowContext(ctx, buscarPersonalizacionPorID, id)
	var i Personalizacion
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Mensaje,
		&i.Color,
	)
	return i, err
}

const buscarProductoPersonalizadoPorID = `-- name: BuscarProductoPersonalizadoPorID :one
SELECT id, pedido_id, nombre, cantidad, precio
FROM producto_personalizado     
WHERE id = ?
`

func (q *Queries) BuscarProductoPersonalizadoPorID(ctx context.Context, id int64) (ProductoPersonalizado, error) {
	row := q.db.QueryRowContext(ctx, buscarProductoPersonalizadoPorID, id)
	var i ProductoPersonalizado
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Nombre,
		&i.Cantidad,
		&i.Precio,
	)
	return i, err
}

const buscarReclamoPorID = `-- name: BuscarReclamoPorID :one
SELECT id, cliente_id, pedido_id, descripcion, estado
FROM Reclamo
WHERE id = ?
`

func (q *Queries) BuscarReclamoPorID(ctx context.Context, id int64) (Reclamo, error) {
	row := q.db.QueryRowContext(ctx, buscarReclamoPorID, id)
	var i Reclamo
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.PedidoID,
		&i.Descripcion,
		&i.Estado,
	)
	return i, err
}

const buscarSeguimientoPedidoPorID = `-- name: BuscarSeguimientoPedidoPorID :one
SELECT id, pedido_id, estado, fecha_estado
FROM SeguimientoPedido
WHERE id = ?
`

func (q *Queries) BuscarSeguimientoPedidoPorID(ctx context.Context, id int64) (Seguimientopedido, error) {
	row := q.db.QueryRowContext(ctx, buscarSeguimientoPedidoPorID, id)
	var i Seguimientopedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Estado,
		&i.FechaEstado,
	)
	return i, err
}

const buscarSlotProduccionPorID = `-- name: BuscarSlotProduccionPorID :one
SELECT id, agenda_id, capacidad_maxima, pedidos_asignados
FROM slotProduccion
WHERE id = ?
`

func (q *Queries) BuscarSlotProduccionPorID(ctx context.Context, id int64) (Slotproduccion, error) {
	row := q.db.QueryRowContext(ctx, buscarSlotProduccionPorID, id)
	var i Slotproduccion
	err := row.Scan(
		&i.ID,
		&i.AgendaID,
		&i.CapacidadMaxima,
		&i.PedidosAsignados,
	)
	return i, err
}

const buscarSolicitudUrgentePorID = `-- name: BuscarSolicitudUrgentePorID :one
SELECT id, cliente, descripcion, fecha_requerida, estado
FROM SolicitudUrgente
WHERE id = ?
`

func (q *Queries) BuscarSolicitudUrgentePorID(ctx context.Context, id int64) (Solicitudurgente, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitudUrgentePorID, id)
	var i Solicitudurgente
	err := row.Scan(
		&i.ID,
		&i.Cliente,
		&i.Descripcion,
		&i.FechaRequerida,
		&i.Estado,
	)
	return i, err
}

const crearAgendaProduccion = `-- name: CrearAgendaProduccion :one
INSERT INTO AgendaProduccion
(fecha, responsable, estado)
VALUES (?, ?, ?)
RETURNING id, fecha, responsable, estado
`

type CrearAgendaProduccionParams struct {
	Fecha       string
	Responsable string
	Estado      string
}

func (q *Queries) CrearAgendaProduccion(ctx context.Context, arg CrearAgendaProduccionParams) (Agendaproduccion, error) {
	row := q.db.QueryRowContext(ctx, crearAgendaProduccion, arg.Fecha, arg.Responsable, arg.Estado)
	var i Agendaproduccion
	err := row.Scan(
		&i.ID,
		&i.Fecha,
		&i.Responsable,
		&i.Estado,
	)
	return i, err
}

const crearCliente = `-- name: CrearCliente :one
INSERT INTO cliente
(nombre, telefono)
VALUES (?, ?)
RETURNING id, nombre, telefono
`

type CrearClienteParams struct {
	Nombre   string
	Telefono string
}

func (q *Queries) CrearCliente(ctx context.Context, arg CrearClienteParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, crearCliente, arg.Nombre, arg.Telefono)
	var i Cliente
	err := row.Scan(&i.ID, &i.Nombre, &i.Telefono)
	return i, err
}

const crearPedido = `-- name: CrearPedido :one
INSERT INTO pedido (mensaje, estado)
VALUES (?, ?)
RETURNING id, mensaje, estado
`

type CrearPedidoParams struct {
	Mensaje string
	Estado  string
}

func (q *Queries) CrearPedido(ctx context.Context, arg CrearPedidoParams) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, crearPedido, arg.Mensaje, arg.Estado)
	var i Pedido
	err := row.Scan(&i.ID, &i.Mensaje, &i.Estado)
	return i, err
}

const crearPersonalizacion = `-- name: CrearPersonalizacion :one
INSERT INTO personalizacion (pedido_id, mensaje, color)
VALUES (?, ?, ?)
RETURNING id, pedido_id, mensaje, color
`

type CrearPersonalizacionParams struct {
	PedidoID int64
	Mensaje  string
	Color    string
}

func (q *Queries) CrearPersonalizacion(ctx context.Context, arg CrearPersonalizacionParams) (Personalizacion, error) {
	row := q.db.QueryRowContext(ctx, crearPersonalizacion, arg.PedidoID, arg.Mensaje, arg.Color)
	var i Personalizacion
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Mensaje,
		&i.Color,
	)
	return i, err
}

const crearProductoPersonalizado = `-- name: CrearProductoPersonalizado :one
INSERT INTO producto_personalizado
(pedido_id, nombre, cantidad, precio)
VALUES (?, ?, ?, ?)
RETURNING id, pedido_id, nombre, cantidad, precio
`

type CrearProductoPersonalizadoParams struct {
	PedidoID int64
	Nombre   string
	Cantidad int64
	Precio   float64
}

func (q *Queries) CrearProductoPersonalizado(ctx context.Context, arg CrearProductoPersonalizadoParams) (ProductoPersonalizado, error) {
	row := q.db.QueryRowContext(ctx, crearProductoPersonalizado,
		arg.PedidoID,
		arg.Nombre,
		arg.Cantidad,
		arg.Precio,
	)
	var i ProductoPersonalizado
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Nombre,
		&i.Cantidad,
		&i.Precio,
	)
	return i, err
}

const crearReclamo = `-- name: CrearReclamo :one
INSERT INTO Reclamo
(cliente_id, pedido_id, descripcion, estado)
VALUES (?, ?, ?, ?)
RETURNING id, cliente_id, pedido_id, descripcion, estado
`

type CrearReclamoParams struct {
	ClienteID   int64
	PedidoID    int64
	Descripcion string
	Estado      string
}

func (q *Queries) CrearReclamo(ctx context.Context, arg CrearReclamoParams) (Reclamo, error) {
	row := q.db.QueryRowContext(ctx, crearReclamo,
		arg.ClienteID,
		arg.PedidoID,
		arg.Descripcion,
		arg.Estado,
	)
	var i Reclamo
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.PedidoID,
		&i.Descripcion,
		&i.Estado,
	)
	return i, err
}

const crearSeguimientoPedido = `-- name: CrearSeguimientoPedido :one
INSERT INTO SeguimientoPedido
(pedido_id, estado, fecha_estado)
VALUES (?, ?, ?)
RETURNING id, pedido_id, estado, fecha_estado
`

type CrearSeguimientoPedidoParams struct {
	PedidoID    int64
	Estado      string
	FechaEstado string
}

func (q *Queries) CrearSeguimientoPedido(ctx context.Context, arg CrearSeguimientoPedidoParams) (Seguimientopedido, error) {
	row := q.db.QueryRowContext(ctx, crearSeguimientoPedido, arg.PedidoID, arg.Estado, arg.FechaEstado)
	var i Seguimientopedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Estado,
		&i.FechaEstado,
	)
	return i, err
}

const crearSlotProduccion = `-- name: CrearSlotProduccion :one
INSERT INTO slotProduccion
(agenda_id, capacidad_maxima, pedidos_asignados)
VALUES (?, ?, ?)
RETURNING id, agenda_id, capacidad_maxima, pedidos_asignados
`

type CrearSlotProduccionParams struct {
	AgendaID         int64
	CapacidadMaxima  int64
	PedidosAsignados int64
}

func (q *Queries) CrearSlotProduccion(ctx context.Context, arg CrearSlotProduccionParams) (Slotproduccion, error) {
	row := q.db.QueryRowContext(ctx, crearSlotProduccion, arg.AgendaID, arg.CapacidadMaxima, arg.PedidosAsignados)
	var i Slotproduccion
	err := row.Scan(
		&i.ID,
		&i.AgendaID,
		&i.CapacidadMaxima,
		&i.PedidosAsignados,
	)
	return i, err
}

const crearSolicitudUrgente = `-- name: CrearSolicitudUrgente :one
INSERT INTO SolicitudUrgente
(cliente, descripcion, fecha_requerida, estado)
VALUES (?, ?, ?, ?)
RETURNING id, cliente, descripcion, fecha_requerida, estado
`

type CrearSolicitudUrgenteParams struct {
	Cliente        string
	Descripcion    string
	FechaRequerida string
	Estado         string
}

func (q *Queries) CrearSolicitudUrgente(ctx context.Context, arg CrearSolicitudUrgenteParams) (Solicitudurgente, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitudUrgente,
		arg.Cliente,
		arg.Descripcion,
		arg.FechaRequerida,
		arg.Estado,
	)
	var i Solicitudurgente
	err := row.Scan(
		&i.ID,
		&i.Cliente,
		&i.Descripcion,
		&i.FechaRequerida,
		&i.Estado,
	)
	return i, err
}

const listarAgendasProduccion = `-- name: ListarAgendasProduccion :many

SELECT id, fecha, responsable, estado
FROM AgendaProduccion
`

// ===================== AGENDAS PRODUCCION =====================
func (q *Queries) ListarAgendasProduccion(ctx context.Context) ([]Agendaproduccion, error) {
	rows, err := q.db.QueryContext(ctx, listarAgendasProduccion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agendaproduccion
	for rows.Next() {
		var i Agendaproduccion
		if err := rows.Scan(
			&i.ID,
			&i.Fecha,
			&i.Responsable,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarClientes = `-- name: ListarClientes :many

SELECT id, nombre, telefono
FROM cliente
`

// ===================== CLIENTES =====================
func (q *Queries) ListarClientes(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, listarClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Telefono); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidos = `-- name: ListarPedidos :many

SELECT id, mensaje, estado
FROM pedido
`

// ===================== PEDIDOS =====================
func (q *Queries) ListarPedidos(ctx context.Context) ([]Pedido, error) {
	rows, err := q.db.QueryContext(ctx, listarPedidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(&i.ID, &i.Mensaje, &i.Estado); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPersonalizaciones = `-- name: ListarPersonalizaciones :many

SELECT id, pedido_id, mensaje, color
FROM personalizacion
`

// ===================== PERSONALIZACIONES =====================
func (q *Queries) ListarPersonalizaciones(ctx context.Context) ([]Personalizacion, error) {
	rows, err := q.db.QueryContext(ctx, listarPersonalizaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Personalizacion
	for rows.Next() {
		var i Personalizacion
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.Mensaje,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarProductosPersonalizados = `-- name: ListarProductosPersonalizados :many

SELECT id, pedido_id, nombre, cantidad, precio
FROM producto_personalizado
`

// ===================== PRODUCTOS PERSONALIZADOS =====================
func (q *Queries) ListarProductosPersonalizados(ctx context.Context) ([]ProductoPersonalizado, error) {
	rows, err := q.db.QueryContext(ctx, listarProductosPersonalizados)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductoPersonalizado
	for rows.Next() {
		var i ProductoPersonalizado
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.Nombre,
			&i.Cantidad,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarReclamos = `-- name: ListarReclamos :many

SELECT id, cliente_id, pedido_id, descripcion, estado
FROM Reclamo
`

// ===================== RECLAMOS =====================
func (q *Queries) ListarReclamos(ctx context.Context) ([]Reclamo, error) {
	rows, err := q.db.QueryContext(ctx, listarReclamos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reclamo
	for rows.Next() {
		var i Reclamo
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.PedidoID,
			&i.Descripcion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSeguimientosPedido = `-- name: ListarSeguimientosPedido :many

SELECT id, pedido_id, estado, fecha_estado
FROM SeguimientoPedido
`

// ===================== SEGUIMIENTO PEDIDOS =====================
func (q *Queries) ListarSeguimientosPedido(ctx context.Context) ([]Seguimientopedido, error) {
	rows, err := q.db.QueryContext(ctx, listarSeguimientosPedido)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seguimientopedido
	for rows.Next() {
		var i Seguimientopedido
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.Estado,
			&i.FechaEstado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSlotsProduccion = `-- name: ListarSlotsProduccion :many

SELECT id, agenda_id, capacidad_maxima, pedidos_asignados
FROM slotProduccion
`

// ===================== SLOTS PRODUCCION =====================
func (q *Queries) ListarSlotsProduccion(ctx context.Context) ([]Slotproduccion, error) {
	rows, err := q.db.QueryContext(ctx, listarSlotsProduccion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slotproduccion
	for rows.Next() {
		var i Slotproduccion
		if err := rows.Scan(
			&i.ID,
			&i.AgendaID,
			&i.CapacidadMaxima,
			&i.PedidosAsignados,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSolicitudesUrgentes = `-- name: ListarSolicitudesUrgentes :many

SELECT id, cliente, descripcion, fecha_requerida, estado
FROM SolicitudUrgente
`

// ===================== SOLICITUDES URGENTES =====================
func (q *Queries) ListarSolicitudesUrgentes(ctx context.Context) ([]Solicitudurgente, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitudesUrgentes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Solicitudurgente
	for rows.Next() {
		var i Solicitudurgente
		if err := rows.Scan(
			&i.ID,
			&i.Cliente,
			&i.Descripcion,
			&i.FechaRequerida,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

